= hw 2 numerical questions

== actual answers

recording my actual answers to they're easy to re-enter...

[options="header"]
.numerical questions
|===
| no. | question | answer
| 1  | Find the source hardware address. |
| 2  | Find the destination hardware address. |
| 3  | What type of frame is this? |
| 4  | What Flag(s) are set? |
| 5  | What is the fragment offset? |
| 6  | What is the TTL count? |
| 7  | What is the Header Checksum? |
| 8  | If the header includes no options or padding, what are the first five
bytes of the datagram data? |
| 9  | Find the destination IP address. |
| 10 |  What class is the destination IP address? |
| 11 |  What is the network ID in the destination address? |
| 12 |  What is the host ID in the destination address? |
| 13 |  Write the destination IP address in dotted decimal notation. |
| 14 |  Find the source IP address. |
| 15 |  What class is the source IP address? |
| 16 |  What is the network ID in the source address? |
| 17 |  What is the host ID in the source address? |
| 18 |  Write the source IP address in dotted decimal notation. |
| 19 |  Can this message be delivered directly by the source to the destination,
or will it require routers to handle the message. |
|===



== hw #2 scratch work

scratch work done for hw #2 while waiting for lecture to start

NOTE: ocr detected free online, for {hw2ipdatagram}[hw 2's ip datagram]

.original
----
C4 BC 6E 3A 5C E7 B9 AA B8 AO OF C3 08 00 45 F9
00 72 E4 D2 78 01 83 CD EB 40 CC 51 2D BB B3 DC
88 4D 41 8E B7 C2 CB 95 C9 68 BD 7B D2 3F D6 DD 
OF 28 20 DD 21 FO ED 32 27 F1 50 3F 89 04 C7 2A 
F2 34 CC D9 34 71 35 F4 98 74 06 BA 93 32 11 E0 
54 06 90 FA 85 FE DF 78 C1 B9 E6 5A 93 75 1C AD
FB 88 10 C2 AA 5F C5 7D 93 97 C1 62 94 3B 89 7F
FC 34 BB 4B 27 6D 92 6C 46 75 OA 86 40 37 4B CA
----

.wrapped at 4 bytes
----
C4 BC 6E 3A
5C E7       # <1>
      B9 AA
B8 AO OF C3 # <2>
08 00       # <3>

            # <4>
      45    # <5>
         F9 # <6>
00 72       # <7>
      E4 D2 # <8> 
7           # <9>
 8 01 83 CD # <10>
EB          # <11>
   40       # <12>
      CC 51 # <13>
2D BB B3 DC # <14>
88 4D 41 8E # <15>
            # <16> <17> <18>
            # <19>
B7 C2 CB 95
C9 68 BD 7B
D2 3F D6 DD
OF 28 20 DD
21 FO ED 32
27 F1 50 3F
89 04 C7 2A
F2 34 CC D9
34 71 35 F4
98 74 06 BA
93 32 11 E0
54 06 90 FA
85 FE DF 78
C1 B9 E6 5A
93 75 1C AD
FB 88 10 C2
AA 5F C5 7D
93 97 C1 62
94 3B 89 7F
FC 34 BB 4B
27 6D 92 6C
46 75 OA 86
40 37 4B CA
----
<1> frame: end of dst hw address
<2> frame: end of src hw address
<3> frame: end of frame type
<4> "ip datagram" ie: start of "frame data" 46-1500 bytes
<5> version & hlen
<6> type of service
<7> total length including payload
<8> identification
<9> fragment flags
<10> fragment offset
<11> ttl
<12> type
<13> header checksum
<14> src ip address
<15> dest ip address
<16> ...
<17> ...
<18> ...
<19> end of ip datagram header
