== lecture 20170911: "IP Protocol"
:hw2ipdatagram: http://comet.lehman.cuny.edu/sfakhouri/teaching/cmp/cmp405/f17/hw/hw2-ipframe.png
:slides: http://comet.lehman.cuny.edu/sfakhouri/teaching/cmp/cmp405/f17/lecturenotes/Chapter%206.pdf

NOTE: {slides}[slides for this lecture]

connectionless packet delivery service
robust

.3 big takeaways
1. internet addressing scheme
2. formats packets
3. routing; ie: packet-forwarding

"packet" == "network packet" == "ip datagram"

.datagram layout
header:: src addr, dest addr, datagram type
data:: payload (comes from layer above IP)


.datagram header layout
|===
| field | byte length | notes
| version | 1/2: 4 bits | eg: `4` == `0100` for ipv4
| header-leng | 1/2: 4 bits | # of rows; ie: total-len / 2 ; our purposes, usually `5`
| type of service | 1 |
| total length | 2 | total byte-length of *header plus payload*
| ident | |
| flags | |
| fragment offset | |
| TTL (time to live) | | usually `225`, ie: `FF`; min-num hops <1>
| type | | 
| header checksum | |
| source ip addr | |
| dest ip addr | |
| skipped | |
| payload/data | | ie: these are first bytes *not* part of header layout
|===
<1> routers decrement TTL value; TTL=0, then packet dropped

NOTE: tcp/ip error handling: detector of errors send back to original sender

.ethernet frame headers:
. 14 bytes
. src hrdwr addr=`0000` (ie: "ip layer gave me this")
. dst hrdw addr
. frame type=`0800` (ie: "ip datagram")

=== mtu & datagram fragmentation

WARN: MTU (max transmission unit) is 1500bytes is a property of NETWORK (ethernet) not of machine or routers

question: what else is there, if everyone is using ethernet? (even wifi/bluetooth)

solution to mtu problem:
 datagram fragmentation send 

mtu applies to the *frame data* size, not the frame itself

question: 64k = 65k535 = 2^16 - 1
  what is this referring to?
  
set fragment offset field of chunked payloads to be equal to the
byte-number (zero-indexed) of the payload within the larger picture of bytes being sent

indicate end-of chunking stream by setting *fragment flag* to `0`
(instead of `1` for "more coming after me")

after first chunk arrives, we set a timer; if *all* fragments don't arrive by time,
then dump everything & return error message

*identification* 2-byte field of ip datagram explains to *which* stream
of chunks a chunk belongs

.fragment flag & offset fields:
flags:: 3 bits
.. 0: reserved, unused
.. dnf (do not forward)
.. more
offset index: 16-3 bits = 13bits; max-index = 2^13 - 1
