= SendReceive Project Usage
:hw6url: http://comet.lehman.cuny.edu/sfakhouri/teaching/cmp/cmp405/f17/hw/hw6.html
:hw9url: http://comet.lehman.cuny.edu/sfakhouri/teaching/cmp/cmp405/f17/hw/hw9.html
:c9d6d689a19ed: https://github.com/jzacsh/netwtcpip-cmp405/tree/c9d6d689a19ed/hw06/
:hw9diff: https://github.com/jzacsh/netwtcpip-cmp405/compare/c9d6d689a19ed...master

== Homework #9

<<hw9instruct, homework 9>> is currently {hw9diff}[in progress]

== Homework #6

status: *complete* as of {c9d6d689a19ed}[`c9d6d689a19ed`] footnoteref:[flagguardhw9,
_should_ still work when not passing `-username USER_NAME` flag introduced by
homework 9; but `git checkout c9d6d689a19ed` to *reliably* see homework 6
solution]

.Build & Run GUI
----
$ make all # or explicitly, the target: bin/Chatterbox.class

$ java -classpath bin Chatterbox
[chatter] Running in forum (GUI) mode
[recv'r thrd] READY to spawn thread consuming from local socket 0.0.0.0/0.0.0.0:6400
[chatter] children spawned, continuing with user task
[recv'r thrd] spawned "recv'r thrd" thread: ForkJoinPool-1-worker-1
[history thrd] spawned "history thrd": ForkJoinPool-1-worker-2
[recv'r thrd] waiting for input...
----

.Run CLI for testing
----
$ java -cp bin Chatterbox -help

$ java -cp bin Chatterbox -1:1 someone.elsese.target.machine:2231
[chatter] setup: listener & sender setups complete.

[chatter] Running in one-to-one (CLI) mode
[recv'r thrd] READY to spawn thread consuming from local socket 0.0.0.0/0.0.0.0:2231
[1:1 thrd] READY to capture messages
        bound for 192.168.86.111:2231
[chatter] children spawned, continuing with user task
[recv'r thrd] spawned "recv'r thrd" thread: ForkJoinPool-1-worker-1
[history thrd] spawned "history thrd": ForkJoinPool-1-worker-2
[1:1 thrd] spawned "1:1 thrd" thread: ForkJoinPool-1-worker-3
[chatter] awaiting single task to exit normally...
[1:1 thrd] CLI usage instructions:
        Type messages & [enter] to send
        [enter] twice to exit.
[recv'r thrd] waiting for input...
----

=== testing receipt on remote machine, `b.lan`

WARNING: this section is outdated and should be ignored

.3 terminals are described below, which you should setup first:
1. on remote `b`, listen for messages: `nc -ul 6400`
2. on local `a`, start app pointing to `b`: `java -cp bin Chatterbox b.lan 6400`
3. second empty/ready terminal on `b` _(to cat into a UDP port; more below)_

... Assume the first two terminals are started, and third blank is opening and
waiting, do the following:

.1: (test) receipt *from* machine `b`
----
you@b $ printf '%s\n' i%0Aam%0Athe%0Awalrus > /dev/udp/a.lan/59105
----

.2: confirm that `a` receives "i am the walrus" on newlines
----
you@a $ java -cp bin Chatterbox b.lan 6400
[chatter] setup: listener & sender setups complete.

[recv'r thrd] READY to spawn thread consuming from local socket 0.0.0.0/0.0.0.0:59105
[recv'r thrd] spawned "recv'r thrd" thread: Thread[recv'r thrd,5,main]
[sender thrd] READY to capture messages
        bound for b.lan/192.168.86.111 on port 6400
        via socket: 0.0.0.0/0.0.0.0:36772
[recv'r thrd] waiting for input...
[sender thrd] spawned "sender thrd" thread: Thread[sender thrd,5,main]
[sender thrd] usage instructions:
        Type messages & [enter] to send
        [enter] twice to exit.
[recv'r thrd] received #001 [994 chars] """
i
am
the
walrus

"""
----

.3: (test) sending *to* remote `b`
----
you @a $ java # ... cli & output snipped from step 2 above

kookoo... kachu??
[sender thrd] sending message #001: 'kookoo... kachu??'... Done.

[sender thrd] press enter again to exit normally.

[sender thrd] caught two empty messages, exiting....
[chatter] cleaning up recvr thread
----

.4: confirm that `b` received step 3 test
----
you@b $ nc -ul 6400
kookoo... kachu??

# or just a `tail`esque version
you@ while true; do echo | nc -ul 6400;done
----

== instructions

<<hw6instruct, below>> is a dump of {hw6url}[homework 6 instructions] as of
2017-10-08 21:17:40-04:00.

[[hw6instruct]]
.homework 6 instructions
----
                                  Homework 6

                       CMP 405: Introduction To Networks
                  Lehman College, City University of New York
                                   Fall 2017

This Homework Is Due By 11:59 PM on Monday October 30, 2017

For this assignment you will be extending what you learned about socket
programming in Datagram Socket Demo

You will be implementing a text messaging application. You will have a seperate
window for each person you are communicating with. The window will have as a
title the IP address and port number of the person you are messaging with.

You will have a main window that allows you to initiate messaging sessions with
other people based on their IP address and port number. Once you initiate a new
messaging session, you will create a new window for that session. This window
should also have a button to exit the program.

You will still have the receiving Thread which will handle all the incoming
messages. However, your code will also keep track of the source IP addresses
and port number along with the window containing that messaging session. If the
source IP address and port number combination is a new one, you will have to
open a new messaging window. Otherwise, the incoming message will be displayed
in the existing window for that source IP address.

Each window will have the following components:

 1. The title of the window should be the IP address and port number of the
    other side of the messaging session.
 2. A section to display the messaging interaction. This window should contain
    the messages from both you and the person you are messaging with.
 3. A section for you to type your reply.
 4. A button to send your reply.
 5. A button the close and end the messaging session.

Please submit your programs in a ZIP file containing all your java programs.

Please do not use packages for your project.

Submit your ZIP file on Blackboard to Homework 6
----

and a dump of {hw9url}[homework 9] pasted below:

[[hw9instruct]]
.homework 9 instructions
----
                                 Homework 9

                      CMP 405: Introduction To Networks
                 Lehman College, City University of New York
                                  Fall 2017

This Homework Is Due By 11:59 PM on Wednesday Decemeber 6, 2017

   For this assignment you will be extending your work from Homework 6.
   This time we will all use the same port number, 64,000.

   You will add a protocol to lookup the IP address of a particular user.

   The protocol should work as follows:
    1. When initiating a messaging session, you will specify the name of
       the person you are trying to reach. This should result in a message
       broadcast to everyone on the local network asking for the IP
       address of the person. This message will be a String formatted as
       follows: "????? name-of-person". Please note that the name of the
       person should be one word with no spaces.
    2. Everyone will receive this message, but only the person wih that
       name will reply with a String formatted as follows: "##### name of
       person ##### ww.xx.yy.zz", where ww.xx.yy.zz is the dotted decimal
       IP address of the person you are trying to message with.
    3. The title of the messaging window should be the name of the person
       you are messaging plus their IP address.

   Please submit your programs in a ZIP file containing all your java
   programs.
   Please do not use packages for your project.
   Submit your ZIP file on Blackboard to Homework 9
----
